# Generated by Django 5.2.6 on 2025-10-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
